### ISSUE TITLE
[BUG]合并单元格后，在合并单元格内部进行添加行、添加列操作，渲染错误

### ISSUE THREAD

**Issue by nekobc1998923** [mengshukeji/Luckysheet#853]
**复现场景：**
1. 先合并一块单元格
2. 鼠标右键在合并单元格内，添加行、添加列。

**gif截图：**
![修改前问题](https://user-images.githubusercontent.com/46434433/142195653-b4874e9f-6d24-43c4-95ad-f4fb90cabb9e.gif)

**Comment by fdsatang** [comment]
2.1.13版本有问题，2.1.12版本正常，今天排查了一下/src/global/extend.js

**Comment by nekobc1998923** [comment]
是的，在extend.js里面有luckysheetextendtable方法，里面对新增行列时初始化了空列模板和空行模板，代码中去取了行列原本的数据，所以mc属性会被留在新增后的行列中，造成渲染问题

**Comment by nekobc1998923** [comment]
我过几天提个PR修复一下

**Comment by fdsatang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mengshukeji/Luckysheet] [BUG]合并单元格后，在合并单元格内部进行添加行、添加列操作，渲染错误 (Issue #853)





 
我过几天提个PR修复一下
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
